public with sharing class BonusAssignment {
	public BonusAssignment() {

		List<String> myList = new List<String>();


		myList.add('comments__c');
		myList.add('!salesRep.Name');
		myList.add('!salesRep.Phone');
		myList.add('!salesRep.Email');
		myList.add('!companyLogo');
		myList.add('Legal_Entity_Registration_Name__c');
		myList.add('Legal_Entity_Registration_Number__c');
		myList.add('Name');
		myList.add('!document.SBQQ__Version__c');
		myList.add('Billing_Account_Number__c');
		myList.add('SBQQ__Status__c');
		myList.add('Formatted_Exp_Date__c');
		myList.add('Payment_Terms_Quote_Doc__c');
		myList.add('Ship_to_Account_Number__c');
		myList.add('End_Customer_Account_Number__c');
		myList.add('SBQQ__ShippingName__c');
		myList.add('Ship_To_Address__c');
		myList.add('End_Customer_Name__c');
		myList.add('End_Customer_Address__c');
		myList.add('FOB__c');
		myList.add('Freight_Terms__c');
		myList.add('Product_Subtotal__c');
		myList.add('Product_Adjustments__c');
		myList.add('Product_Total__c');
		myList.add('Service_Subtotal__c');
		myList.add('Service_Adjustments__c');
		myList.add('Service_Total__c');
		myList.add('Freight_Subtotal__c');
		myList.add('Freight_Adjustments__c');
		myList.add('Freight_Total__c');
		myList.add('Original_Extended_Amount__c');
		myList.add('Total_Adjustments__c');
		myList.add('SBQQ__NetAmount__c');
		myList.add('SBQQ__BillingName__c');
		myList.add('Bill_To_Address__c');
		myList.add('Legal_Entity_Address_Name__c');
		myList.add('Legal_Entity_Address__c');
		
		
	}
}